# Senior Clinical Data Engineer Coding Challenge
by Yanting (Emma) Cao

July 30, 2019

## Read the following files into a dataframe:

In [1]:
# import library
import pandas as pd

# read files into dataframe
ec = pd.read_csv('t2_ec 20190619.csv')
ec = ec.dropna(how="all")
registry = pd.read_csv('t2_registry 20190619.csv')

In [2]:
print('ec dataframe contains',ec.shape[0],'rows and', ec.shape[1],'columns.')
print('registry dataframe contains', registry.shape[0],'rows and', registry.shape[1],'columns.')

ec dataframe contains 11 rows and 23 columns.
registry dataframe contains 14 rows and 18 columns.

## Merge the dataframes
Left merge on registry, merge on RID and VISCODE, new dataframe is named registry_ec

In [3]:
registry_ec = pd.merge(registry, ec, on = ['RID','VISCODE'], how = 'left')

registry_ec = registry_ec.rename(columns = {'ID_x':'registry.ID','ID_y':'ec.ID',
                              'USERID_x': 'registry.USERID', 'USERID_y':'ec.USERID'})

## Filter records

### Filter where registry.viscode is w02

In [4]:
filter_viscode_w02 = registry_ec[registry_ec['VISCODE'] == 'w02']
filter_viscode_w02

,registry.ID,SX_x,RID,SITEID_x,VISCODE,ENTRY_x,VERIFY_x,registry.USERID,USERDATE_x,USERID2_x,...,ECENDAT,ECOCCUR,ECREASOC,REASOTH,ECSDSTXT,ECDOSU,ECDOSFRQ,ECDOSADJ,ECADJ,ECADJOTH
4,14,-4,20,2,w02,4,4,BBAGGINS_UCSD_EDU_2,8/24/18,NaN,...,2/18/19,Y,-4,-4,280.0,mg,QD,Y,PER PROTOCOL,-4.0
12,30,-4,19,1,w02,4,4,MORPHEUS_UCSD_EDU_2,8/9/18,NaN,...,2/2/19,N,OTHER,Test,-4.0,-4,-4,-4,-4,-4.0
13,32,-4,17,2,w02,4,4,MORPHEUS_UCSD_EDU,8/9/18,NaN,...,NaN,Y,-4,-4,140.0,mg,QD,Y,PER PROTOCOL,NaN

### Filter where registry.SVDOSE is Y

In [5]:
filter_svdose_y = registry_ec[registry_ec['SVDOSE'] == 'Y']
filter_svdose_y

,registry.ID,SX_x,RID,SITEID_x,VISCODE,ENTRY_x,VERIFY_x,registry.USERID,USERDATE_x,USERID2_x,...,ECENDAT,ECOCCUR,ECREASOC,REASOTH,ECSDSTXT,ECDOSU,ECDOSFRQ,ECDOSADJ,ECADJ,ECADJOTH
4,14,-4,20,2,w02,4,4,BBAGGINS_UCSD_EDU_2,8/24/18,NaN,...,2/18/19,Y,-4,-4,280.0,mg,QD,Y,PER PROTOCOL,-4.0
12,30,-4,19,1,w02,4,4,MORPHEUS_UCSD_EDU_2,8/9/18,NaN,...,2/2/19,N,OTHER,Test,-4.0,-4,-4,-4,-4,-4.0
13,32,-4,17,2,w02,4,4,MORPHEUS_UCSD_EDU,8/9/18,NaN,...,NaN,Y,-4,-4,140.0,mg,QD,Y,PER PROTOCOL,NaN

### Filter where registry.ECSDSTXT is not 280

In [6]:
# where registry.viscode is w02
filter_ecsdstxt_not280 = registry_ec[registry_ec['ECSDSTXT'] != 280]
filter_ecsdstxt_not280

,registry.ID,SX_x,RID,SITEID_x,VISCODE,ENTRY_x,VERIFY_x,registry.USERID,USERDATE_x,USERID2_x,...,ECENDAT,ECOCCUR,ECREASOC,REASOTH,ECSDSTXT,ECDOSU,ECDOSFRQ,ECDOSADJ,ECADJ,ECADJOTH
0,6,-4,19,1,sc,4,4,AELGIN_UCSD_EDU_2,8/9/18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8,-4,17,2,sc,4,4,AMMCGEE_UCSD_EDU,8/9/18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10,-4,20,2,sc,4,4,BBAGGINS_UCSD_EDU_2,8/9/18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,12,-4,20,2,bl,4,4,BBAGGINS_UCSD_EDU_2,8/10/18,NaN,...,8/10/18,Y,-4,-4,140.0,mg,QD,N,-4,-4.0
5,16,-4,20,2,w04,4,4,BBAGGINS_UCSD_EDU_2,9/24/18,NaN,...,8/10/18,N,OTHER,Test,-4.0,-4,-4,-4,-4,-4.0
6,18,-4,20,2,w08,4,4,BBAGGINS_UCSD_EDU_2,10/24/18,NaN,...,8/10/18,Y,-4,-4,200.0,mg,QD,N,-4,-4.0
7,20,-4,20,2,w12,4,4,BBAGGINS_UCSD_EDU_2,11/24/18,NaN,...,8/10/18,Y,-4,-4,200.0,mg,QD,N,-4,-4.0
8,22,-4,20,2,w24,4,4,BBAGGINS_UCSD_EDU_2,2/24/19,NaN,...,-4,Y,-4,-4,200.0,mg,QD,N,-4,-4.0
9,24,-4,20,2,w36,4,4,BBAGGINSD_UCSD_EDU_2,5/24/19,NaN,...,-4,Y,-4,-4,200.0,mg,QD,N,-4,-4.0
11,28,-4,17,2,bl,4,4,STARBUCK_UCSD_EDU,8/9/18,NaN,...,8/17/18,Y,-4,-4,200.0,mg,QD,N,-4,-4.0
12,30,-4,19,1,w02,4,4,MORPHEUS_UCSD_EDU_2,8/9/18,NaN,...,2/2/19,N,OTHER,Test,-4.0,-4,-4,-4,-4,-4.0
13,32,-4,17,2,w02,4,4,MORPHEUS_UCSD_EDU,8/9/18,NaN,...,NaN,Y,-4,-4,140.0,mg,QD,Y,PER PROTOCOL,NaN

## Create new .csv file
Since registry and ec contain different ID and USERID, use registry.ID, registry.USERID, ec.ID, ec.USERID to denote ID and USERID from their respective dataframes.

In [7]:
# include the following columns in result 
result = registry_ec[['registry.ID','ec.ID','RID','registry.USERID','ec.USERID','VISCODE',
            'SVDOSE','ECSDSTXT']]

In [8]:
# write result to result.csv, not including pandas dataframe index
result.to_csv('result.csv', index = False)